
export const MANIFOLD_CONSTANTS = {
  ANIMATION_DYNAMICS: {
    expandedEnvelope: 7.2,
    manifoldMode2D: 5.2,
    manifoldMode4D: 4.8,
    hyperspaceMorph: 3.15,
    lateralPanFast: 7.2,
    lateralPanBase: 5.4,
    introEnvelope: 5.8,
    exitEnvelope: 4.4,
    hudFocusHoldMs: 100,
    hudRefreshMs: 100,
    performanceModeDebounceMs: 280,
    fullRateSamplingMs: 220,
    expandedMotionQuenchMs: 220,
    reverseExpandedMotionQuenchMs: 320,
    expandedOpenImmediateVelocityScale: 0.08,
    expandedMotionVelocityScale: 0.12,
    expandedMotionSustainVelocityScale: 0.28,
    expandedMotionReverseVelocityScale: 0.14,
    reverseExpandImmediateVelocityScale: 0.05,
    expandedMotionScrollLerp: 0.12,
    expandedMotionSustainScrollLerp: 0.18,
    reverseCardPrewarmOpacityFloor: 0.016,
    velocitySmoothingLerp: 0.05,
    frameTimeEmaLerp: 0.12,
    frameTimeBurstDecayLerp: 0.04,
    fpsRiseLerp: 0.22,
    fpsFallLerp: 0.1,
    zenPointerReturnLerp: 0.14,
    topbarRiseLerp: 0.22,
    topbarFallLerp: 0.09,
    particleRiseLerp: 0.025,
    particleFallLerp: 0.014,
    perspectiveNear: 1000,
    perspectiveFar: 2600,
    sectionFrameEnvelope: 10.5,
    sectionFrameVisualEnvelope: 8.4,
    cardFastVisualEnvelope: 7.6
  },
  CARD_MOTION: {
    ambientLiftAmplitude: 5.4,
    ambientLiftFrequencyBase: 0.82,
    ambientLiftFrequencyVariance: 0.26,
    ambientLiftPhaseVariance: 6,
    inertiaVelocityBase: 18,
    inertiaVelocityVariance: 10,
    inertiaVelocityClamp: 120,
    rotXVelocityScalar: -0.14,
    rotXClamp: 5.2,
    rotXWaveFrequency: 0.7,
    rotXWavePhaseVariance: 4,
    rotXWaveAmplitude: 0.35,
    rotYWaveFrequency: 0.9,
    rotYWavePhaseVariance: 9,
    rotYWaveAmplitude: 7.5,
    rotYMouseBase: 0.16,
    rotYMouseVariance: 0.12,
    rotZWaveFrequency: 1,
    rotZWavePhaseVariance: 8,
    rotZWaveAmplitude: 0.16,
    inertiaZResponse: 0.28,
    inertiaYResponse: 0.58,
    inertiaRotZResponse: 0.32,
    inertiaRotYResponse: 0.28,
    inertiaRotXResponse: 0.22,
    introFloatTimeScalar: 0.0012,
    introFloatAmplitude: 10,
    introShiftZ: 18
  },
  AUDIO_REACTIVE: {
    waveFrequency: 0.018,
    waveVariancePhase: 7.4,
    scrollHeavyBaseOffset: 2,
    scrollHeavyStrengthMultiplier: 10,
    baseOffset: 3.2,
    strengthMultiplier: 22,
    shiftRiseLerp: 0.36,
    shiftFallLerp: 0.18,
    chromaRiseLerp: 0.34,
    chromaFallLerp: 0.14
  },
  TESSERACT_PHYSICS: {
    faceCardExtent: 220,
    hyperSpinScalar: 2.1,
    yzSpinScalar: 0.58,
    zwSpinScalar: 0.34,
    xySpinScalar: 0.16,
    yzTimeScalar: 0.00018,
    zwTimeScalar: 0.00012,
    xyTimeScalar: 0.00006,
    wLensOrigin: 2.9,
    wLensFloor: 0.72,
    zLensOrigin: 3.8,
    zLensFloor: 0.72,
    screenScaleFactor: 1.8,
    depthNear: -0.9,
    depthSpan: 1.8,
    diagonalCullFloor: 24,
    determinantEpsilon: 0.000001,
    faceZIndexBase: 20
  },
  INTERACTION_SENSITIVITY: {
    clickTravelThreshold: 14,
    hoverRetentionInset: 18,
    hoverFallbackInset: 42,
    idleHintDelayMs: 5000,
    idleVelocityFloor: 0.04,
    fastTwoDVelocity: 0.24,
    horizontalIntentThreshold: 10,
    horizontalIntentRatio: 0.55,
    stackedMobileHorizontalBlock: 10
  },
  LAYOUT_GRID: {
    desktopColumns: 3,
    mobileColumns: 2,
    stackedColumns: 1,
    stackedPortraitRatio: 1.08,
    mobileGridScale: 1.08,
    desktopGridScale: 1.12,
    stackedGridScale: 1.02,
    compactCardWidth: 320,
    compactCardHeight: 460,
    expandedDesktopViewportWidth: 0.78,
    expandedDesktopViewportHeight: 0.74,
    expandedMobileViewportWidth: 0.9,
    expandedMobileViewportHeight: 0.78
  },
  SPATIAL_TOPOLOGY: {
    featuredDockZ: -220,
    featuredIntroZ: -248,
    featuredIntroX: -62,
    featuredIntroY: 60,
    featuredIntroRotZ: -12.5,
    featuredIntroTiltX: -2.8,
    featuredIntroScale: 1.115,
    entryGridLift: 18,
    sectionRepulsionRadius: 760,
    sectionRepulsionStrength: 52,
    reverseCardPrewarmRearLimit: 960,
    fourDSourceFadeOffset: 0.08,
    fourDSourceFadeSpan: 0.24,
    fourDSourceRestoreOffset: 0.05,
    fourDSourceRestoreSpan: 0.34,
    overlayPresenceOffset: 0.06,
    overlayPresenceSpan: 0.8,
    overlayGeometryOffset: 0.14,
    overlayGeometrySpan: 0.72,
    wireframePresenceOffset: 0.18,
    wireframePresenceSpan: 0.7
  },
  PERFORMANCE_THRESHOLDS: {
    fastModeViewThreshold: 0.55,
    fastVelocityFloor: 0.24,
    frameStressEmaMultiplier: 1.16,
    frameStressBurstMultiplier: 1.9
  }
} as const;

export const SCROLL_CLOSE_KEYS = new Set([
  'ArrowUp',
  'ArrowDown',
  'PageUp',
  'PageDown',
  'Home',
  'End',
  ' ',
  'Spacebar'
]);
