export const MANIFOLD_AUDIO_TARGET_VOLUME = 0.95;
export const MANIFOLD_ZEN_SCROLL_SPEED_PX_PER_MS = 0.2;
export const MANIFOLD_LOOP_MULTIPLIER = 72;
export const MANIFOLD_LOOP_REBASE_MARGIN_LOOPS = 6;
export const MANIFOLD_LOOP_REBASE_EMERGENCY_MARGIN_LOOPS = 1.5;
export const MANIFOLD_LOOP_REBASE_DEFER_VELOCITY = 0.9;
export const MANIFOLD_SCRAMBLE_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789#/<>*+=-';
